# Generated by Django 4.2.7 on 2025-10-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.CharField(max_length=100, verbose_name='ID do Respondente')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Respondente')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Resposta da Pesquisa',
                'verbose_name_plural': 'Respostas das Pesquisas',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'respondent_id')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto da Pergunta')),
                ('question_type', models.CharField(choices=[('nps', 'NPS (0-10)'), ('text', 'Texto Livre'), ('choice', 'Múltipla Escolha'), ('rating', 'Avaliação (1-5)')], max_length=10, verbose_name='Tipo')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Texto da Opção')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NPSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('total_responses', models.PositiveIntegerField(verbose_name='Total de Respostas')),
                ('promoters', models.PositiveIntegerField(verbose_name='Promotores (9-10)')),
                ('passives', models.PositiveIntegerField(verbose_name='Neutros (7-8)')),
                ('detractors', models.PositiveIntegerField(verbose_name='Detratores (0-6)')),
                ('nps_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score NPS')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado em')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_results', to='surveys.survey', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Resultado NPS',
                'verbose_name_plural': 'Resultados NPS',
                'ordering': ['-calculated_at'],
                'unique_together': {('survey', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Resposta em Texto')),
                ('answer_value', models.CharField(blank=True, max_length=100, verbose_name='Valor da Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.choice', verbose_name='Opção Escolhida')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Pergunta')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
