# Generated by Django 4.2.7 on 2025-11-05 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, verbose_name='Permitir múltiplas respostas'),
        ),
        migrations.AddField(
            model_name='survey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Destinatário')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token Único')),
                ('is_used', models.BooleanField(default=False, verbose_name='Já Utilizado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Convite de Pesquisa',
                'verbose_name_plural': 'Convites de Pesquisa',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'email')},
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='surveys.surveyinvitation', verbose_name='Convite'),
        ),
    ]
