# Generated by Django 4.2.7 on 2025-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_allow_multiple_responses_survey_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Usuário')),
                ('nome_conta', models.CharField(blank=True, max_length=200, verbose_name='Nome da Conta')),
                ('nome_usuario', models.CharField(blank=True, max_length=200, verbose_name='Nome do Usuário')),
                ('status_usuario', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Bloqueado', 'Bloqueado'), ('Pendente', 'Pendente')], default='Ativo', max_length=50, verbose_name='Status do Usuário')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Respondente',
                'verbose_name_plural': 'Respondentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
