# Generated by Django 4.2.7 on 2025-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvitation',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Cliques'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link Clicado em'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Aberturas'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aberto em'),
        ),
        migrations.AddField(
            model_name='surveyinvitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
    ]
