# Generated by Django 4.2.7 on 2025-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveyinvitation_click_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Produto'),
        ),
    ]
